create table if not exists public.contacto (
    id bigint generated by default as identity primary key,
    nombreCompleto text not null,
    email text not null,
    telefono text not null,
    mensaje text not null,
    created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists contacto_created_at_idx
    on public.contacto (created_at desc);

alter table public.contacto enable row level security;

drop policy if exists "contacto_service_role_all" on public.contacto;

create policy "contacto_service_role_all"
    on public.contacto
    for all
    to service_role
    using (true)
    with check (true);
