create table if not exists public.noticias (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text not null,
  "imageUrl" text not null,
  fecha date not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists set_noticias_updated_at on public.noticias;
create trigger set_noticias_updated_at
before update on public.noticias
for each row
execute function public.set_updated_at_timestamp();

alter table public.noticias enable row level security;

grant select, insert, update, delete on table public.noticias to anon, authenticated;
grant usage, select on sequence public.noticias_id_seq to anon, authenticated;

drop policy if exists "Public can read noticias" on public.noticias;
create policy "Public can read noticias"
on public.noticias
for select
to public
using (true);

drop policy if exists "Anon can insert noticias" on public.noticias;
create policy "Anon can insert noticias"
on public.noticias
for insert
to anon
with check (true);

drop policy if exists "Anon can update noticias" on public.noticias;
create policy "Anon can update noticias"
on public.noticias
for update
to anon
using (true)
with check (true);

drop policy if exists "Anon can delete noticias" on public.noticias;
create policy "Anon can delete noticias"
on public.noticias
for delete
to anon
using (true);

insert into storage.buckets (id, name, public)
values ('noticias', 'noticias', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public can read noticias images" on storage.objects;
create policy "Public can read noticias images"
on storage.objects
for select
to public
using (bucket_id = 'noticias');

drop policy if exists "Anon can upload noticias images" on storage.objects;
create policy "Anon can upload noticias images"
on storage.objects
for insert
to anon
with check (bucket_id = 'noticias');

drop policy if exists "Anon can update noticias images" on storage.objects;
create policy "Anon can update noticias images"
on storage.objects
for update
to anon
using (bucket_id = 'noticias')
with check (bucket_id = 'noticias');

drop policy if exists "Anon can delete noticias images" on storage.objects;
create policy "Anon can delete noticias images"
on storage.objects
for delete
to anon
using (bucket_id = 'noticias');
